include: package:effective_dart/analysis_options.yaml

linter:
    rules:
      prefer_relative_imports: false
      omit_local_variable_types: false
      unnecessary_this: false
      lines_longer_than_80_chars: false
      avoid_classes_with_only_static_members: false
      public_member_api_docs: false
      avoid_types_on_closure_parameters: false
