name: $(Rev:r:)

jobs:
  - job: sudoku_solver_2
    timeoutInMinutes: 30
    pool:
      vmImage: "ubuntu:18.04"

    container: lachie.azurecr.io/flutter-container:latest

    steps:
      - task: PowerShell@2
        displayName: Pull Container
        inputs:
          targetType: "inline"
          script: |
            Write-Host "Container was pulled"
