name: $(Rev:r:)

jobs:
  - job: sudoku-solver-2
    timeoutInMinutes: 30
    pool:
      vmImage: "macOS-latest"

    steps:
      - task: FlutterInstall@0
        displayName: Setup Flutter
        inputs:
          channel: 'stable'
          version: 'latest'

      - task: SonarQubePrepare@4
        displayName: Setup SonarQube
        inputs:
          SonarQube: 'sonarqube'
          scannerMode: 'CLI'
          configMode: 'file'
          projectKey: 'sudoku-solver-2'
          projectName: 'sudoku-solver-2'
          extraProperties: |
            sonar.projectKey=sudoku-solver-2
            sonar.projectName=sudoku-solver-2
            sonar.projectVersion=1.0
            sonar.sourceEncoding=UTF-8

            # source files
            sonar.source=lib
            # unit test files
            sonar.test=test
            
            # folders to exclude in scan
            sonar.exclusions= android/**, ios/**

      - task: PowerShell@2
        displayName: Setup Environment
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"

      - task: CmdLine@2
        displayName: Run Unit Tests
        inputs:
          script: |
          'flutter pub get'
          'flutter test --machine > tests.output'
          'flutter test --coverage'

      - task: SonarQubeAnalyze@4
        displayName: Run Quality Scan

      - task: SonarQubePublish@4
        displayName: Publish Scan Results
        inputs:
          pollingTimeoutSec: '300'