name: $(Rev:r:)

jobs:
  - job: sudoku_solver_2
    timeoutInMinutes: 30
    pool:
      vmImage: "macOS-latest"

    steps:
      # - task: FlutterInstall@0
      #   displayName: Setup Flutter
      #   inputs:
      #     channel: "stable"
      #     version: "latest"

      - task: SonarQubePrepare@4
        displayName: Setup SonarQube
        inputs:
          SonarQube: "sonarqube"
          scannerMode: "CLI"
          configMode: "file"

      - task: PowerShell@2
        displayName: Setup Environment
        inputs:
          targetType: "inline"
          script: |
            # Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            # Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            # Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            # Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"
            # #install flutter sonarqube plugin


            $x = $Env:Path
            Write-Host $x


            $url = "https://github.com/insideapp-oss/sonar-flutter/releases/download/0.3.1/sonar-flutter-plugin-0.3.1.jar"
            $output = "extensions/plugins/flutter-sonarqube-plugin.jar"
            Invoke-WebRequest -Uri $url -OutFile $output

      # - task: CmdLine@2
      #   displayName: Run Unit Tests
      #   inputs:
      #     script: |
      #       # Download dependencies
      #       flutter pub get
      #       # Run tests
      #       flutter test --machine > tests.output
      #       # Compute coverage (--machine and --coverage cannot be run at once...)
      #       flutter test --coverage
      #       # Run the analysis and publish to the SonarQube server
      #       sonar-scanner
