name: $(Rev:r:)

trigger:
  - master

jobs:
  - job: Test
    timeoutInMinutes: 20
    pool:
      vmImage: "macOS-latest"

    steps:
      - script: sudo chown
        displayName: Grant permissions
      - script: azure/pipelines/scripts.sh install_flutter
        displayName: Install Flutter
      - script: azure/pipelines/scripts.sh flutter_test
        displayName: Test app
      - script: ../azure/pipelines/scripts.sh pull_video
        displayName: Pull screen video record
        condition: always()
      - task: PublishBuildArtifacts@1
        displayName: Publish screenshots
        condition: always()
        inputs:
          pathtoPublish: "$(System.DefaultWorkingDirectory)/screenshots/"
          artifactName: screenshots
