name: $(Rev:r:)

jobs:
  - job: build_and_test
    timeoutInMinutes: 30
    pool:
      vmImage: "macOS-latest"

    steps:
      - script: sudo chmod +x azure/pipelines/scripts.sh
        displayName: Grant Shell Permissions

      #   - task: Cache@2
      #     inputs:
      #       key: flutterKey
      #       restoreKeys: flutterKey
      #       path: /Users/runner/work/1/s/flutter
      #       cacheHitVar: FLUTTER_CACHE_RESTORED

      - task: FlutterInstall@0
        displayName: Setup flutter
        inputs:
          channel: stable
          version: latest

      - task: CmdLine@2
        displayName: Run test
        inputs:
          script: "flutter test --machine > tests.output"

      - script: echo $PATH
        displayName: do stuff

    #   - task: Cache@2
    #     inputs:
    #       key: emulatorKey
    #       restoreKeys: emulatorKey
    #       path: $ANDROID_HOME
    #       cacheHitVar: EMULATOR_CACHE_RESTORED


    #   - script: azure/pipelines/scripts.sh setup_emulator
    #     displayName: Setup Emulator
    #     condition: ne(variables.EMULATOR_CACHE_RESTORED, 'true')


    #   - script: azure/pipelines/scripts.sh run_integration_tests
    #     displayName: Run Integration Tests
