name: $(Rev:r:)

trigger:
  - master

jobs:
  - job: Test
    timeoutInMinutes: 20
    pool:
      vmImage: "macOS-latest"

    steps:
      - script: sudo chmod +x azure/pipelines/scripts.sh
        displayName: Grant Shell Permissions
      - script: azure/pipelines/scripts.sh install_flutter
        displayName: Install Flutter
      - script: azure/pipelines/scripts.sh run_unit_tests
        displayName: Run Unit Tests
      - script: azure/pipelines/scripts.sh setup_emulator
        displayName: Setup Emulator
      - script: azure/pipelines/scripts.sh start_app
        displayName: Start App
      - script: azure/pipelines/scripts.sh run_integration_tests
        displayName: Run Integration Tests
      - script: echo SUCCESS
        displayName: Verify

