name: $(Rev:r:)

trigger:
  - master

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

jobs:
  - job: Test
    timeoutInMinutes: 20
    pool:
      vmImage: "macOS-latest"

    steps:
      - script: sudo chmod +x azure/pipelines/scripts.sh
        displayName: Grant Shell Permissions

      - task: Cache@2
        inputs:
          key: flutterKey
          restoreKeys: flutterKey
          path: $(Pipeline.Workspace)/flutter
          cacheHitVar: FLUTTER_CACHE_RESTORED

      - script: azure/pipelines/scripts.sh install_flutter
        displayName: Install Flutter
        condition: ne(variables.FLUTTER_CACHE_RESTORED, 'true')

      - script: azure/pipelines/scripts.sh run_unit_tests
        displayName: Run Unit Tests

      - task: Cache@2
        inputs:
          key: emulatorKey
          restoreKeys: emulatorKey
          path: $ANDROID_HOME
          cacheHitVar: EMULATOR_CACHE_RESTORED

      - script: azure/pipelines/scripts.sh setup_emulator
        displayName: Setup Emulator
        condition: ne(variables.EMULATOR_CACHE_RESTORED, 'true')

      - script: azure/pipelines/scripts.sh run_integration_tests
        displayName: Run Integration Tests

    #   - task: Cache@2
    #     displayName: cache everything
    #     inputs:
    #       key: 'everything | "$(Agent.OS)"'
    #       restoreKeys: everything
    #       path: $(Pipeline.Workspace)
