name: $(Rev:r:)

jobs:
  - job: sudoku_solver_2
    timeoutInMinutes: 30
    pool:
      vmImage: "ubuntu-16.04"

    container: flutter-container.eastus.azurecontainer.io

    steps:
      - task: PowerShell@2
        displayName: Integration Tests
        inputs:
          targetType: "inline"
          script: |
            echo "Running Integration Tests"
            flutter drive --target=test_driver/run_app.dart
