name: $(Rev:r:)

jobs:
  - job: build_and_test
    timeoutInMinutes: 30
    pool:
      vmImage: "macOS-latest"

    steps:
      - script: sudo chmod +x azure/pipelines/scripts.sh
        displayName: Grant Shell Permissions

      - task: Cache@2
        inputs:
          key: flutterKey
          restoreKeys: flutterKey
          path: ~/flutter
          cacheHitVar: FLUTTER_CACHE_RESTORED

      - script: azure/pipelines/scripts.sh install_flutter
        displayName: Install Flutter
        condition: ne(variables.FLUTTER_CACHE_RESTORED, 'true')

      - script: azure/pipelines/scripts.sh run_unit_tests
        displayName: Run Unit Tests

      - task: Cache@2
        inputs:
          key: emulatorKey
          restoreKeys: emulatorKey
          path: $ANDROID_HOME
          cacheHitVar: EMULATOR_CACHE_RESTORED

      - script: azure/pipelines/scripts.sh setup_emulator
        displayName: Setup Emulator
        condition: ne(variables.EMULATOR_CACHE_RESTORED, 'true')

      - script: azure/pipelines/scripts.sh run_integration_tests
        displayName: Run Integration Tests
