name: $(Rev:r:)

jobs:
  - job: sudoku_solver_2
    timeoutInMinutes: 30
    pool:
      vmImage: "macOS-latest"

    steps:
      - task: PowerShell@2
        displayName: Pull Container
        inputs:
          targetType: "inline"
          script: |
          docker pull lachie.azurecr.io/flutter-container:latest
          Write-Host "Container was pulled"