name: $(Rev:r:)

jobs:
  - job: Sudoku Solver 2
    timeoutInMinutes: 30
    pool:
      vmImage: "macOS-latest"

    steps:
      - task: FlutterInstall@0
        displayName: Setup Flutter
        inputs:
          channel: 'stable'
          version: 'latest'

      - task: SonarQubePrepare@4
        displayName: Setup SonarQube
        inputs:
          SonarQube: 'sonarqube'
          scannerMode: 'CLI'
          configMode: 'file'


      - task: PowerShell@2
        displayName: Setup Environment
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"

      - task: CmdLine@2
        inputs:
          script: |
            flutter pub get
            flutter test --machine > tests.output
            flutter test --coverage

      - task: SonarQubeAnalyze@4
        displayName: Run Quality Scan

      - task: SonarQubePublish@4
        displayName: Publish Scan Results
        inputs:
          pollingTimeoutSec: '300'