name: $(Rev:r:)

jobs:
  - job: Run_My_Pipeline
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-latest

    steps:
      - script: sudo chmod +x pipeline-scripts.sh
        displayName: Grant Shell Permissions

      - script: pipeline-scripts.sh install_flutter
        displayName: Install Flutter

      - script: pipeline-scripts.sh run_unit_tests
        displayName: Run Unit Tests

      - script: pipeline-scripts.sh install_emulator
        displayName: Install Emulator

      - script: pipeline-scripts.sh run_emulator
        displayName: Run Emulator

      - script: pipeline-scripts.sh run_integration_tests
        displayName: Run Integration Tests

      - script: pipeline-scripts.sh calculate_test_coverage
        displayName: Calculate Test Coverage

      - task: SonarQubePrepare@4
        displayName: Start SonarQube
        inputs:
          SonarQube: sonarqube-flutter
          scannerMode: CLI
          configMode: file

      - task: SonarQubeAnalyze@4
        displayName: Analyse SonarQube

      - task: SonarQubePublish@4
        displayName: Publish SonarQube Results
        inputs:
          pollingTimeoutSec: 300
