name: sudoku_solver_2
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: 
    git:
      url: https://github.com/lachiejames/plugins.git
  cupertino_icons: ^0.1.3
  flutter_redux: ^0.6.0
  path_provider: any
  redux_thunk: ^0.3.0
  shared_preferences: ^0.5.8
  image: ^2.1.12
  firebase_core: ^0.5.3
  firebase_ml_vision: ^0.9.4
  async: ^2.4.2
  native_device_orientation: ^0.4.3
  firebase_analytics: ^6.3.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.1
  effective_dart: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
