name: sudoku_solver_2
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  audioplayers: ^0.16.1
  camera: ^0.5.8+17
  firebase_admob: ^0.10.3
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_ml_vision: ^0.9.10
  firebase_performance: "^0.4.3"
  flutter_redux: ^0.7.0
  image: ^2.1.19
  path_provider: ^1.6.24
  redux_thunk: ^0.3.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  effective_dart: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
